@startuml

title __SEM's Class Diagram__\n

  namespace com.napier.sem {
    class com.napier.sem.App {
        - con : Connection
        + connect()
        + disconnect()
        + displayCity()
        + getAllCities()
        + getAllCountries()
        + getCitiesByLargestPopulationInCountry()
        + getCity()
        {static} + main()
    }
  }
  

  namespace com.napier.sem {
    class com.napier.sem.City {
        - country_code : String
        - district : String
        - id : int
        - name : String
        - population : int
        + City()
        + getCountry_code()
        + getDistrict()
        + getId()
        + getName()
        + getPopulation()
        + toString()
    }
  }
  

  namespace com.napier.sem {
    class com.napier.sem.Country {
        - GNP : double
        - GNPOld : double
        - ISO2Code : String
        - ISO3Code : String
        - capital : int
        - continent : String
        - governmentForm : String
        - headOfState : String
        - independenceYear : int
        - lifeExpectancy : double
        - localName : String
        - name : String
        - population : int
        - region : String
        - surfaceArea : Double
        + Country()
        + getCapital()
        + getContinent()
        + getGNP()
        + getGNPOld()
        + getGovernmentForm()
        + getHeadOfState()
        + getISO2Code()
        + getISO3Code()
        + getIndependenceYear()
        + getLifeExpectancy()
        + getLocalName()
        + getName()
        + getPopulation()
        + getRegion()
        + getSurfaceArea()
        + toString()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
